feat(install): support for scala/java search through maven.org & auto-resolve!

diff --git a/sbti b/sbti
--- a/sbti
+++ b/sbti
@@ -69,13 +69,47 @@ Press ^C at any time to quit."
     ;;
 
   install)
-    dep=(${2//// })
-    groupID=${dep[0]}
-    dep=(${dep[1]//@/ })
-    artifactID=${dep[0]}
-    revision=${dep[1]}
+    SEARCH_QUERY=$2
+    SEARCH_SIZE=20
+    # SEARCH_RESULTS=`curl --silent "http://search.maven.org/solrsearch/select?q=${SEARCH_QUERY}&rows=${SEARCH_SIZE}&wt=json"`
+    # if [ $? != 0 ]; then
+    #   echo 'An error occured while search on maven.org.';
+    #   exit 1;
+    # fi
+
+    # I will keep this line just to remember myself that the above code was done on a friday night train to Paris without internet (4th September 2015)
+    SEARCH_RESULTS=`cat results.json`
+
+    MENU_OPTIONS=`echo ${SEARCH_RESULTS} | jq -r '.response.docs[].id'`
+    MENU_TEXT="Select library for '${SEARCH_QUERY}'"
+    MENU_YES_LABEL="Add to ${SBT_FILE}"
+
+    SELECTED_LIBRARY=`dialog --stdout \
+      --ok-label "${MENU_YES_LABEL}" \
+      --scrollbar \
+      --title "${SBTI}" \
+      --yes-label "${MENU_YES_LABEL}" \
+      --no-items \
+      --menu "${MENU_TEXT}" 25 55 $SEARCH_SIZE $(echo $MENU_OPTIONS)`
+
+    clear
+
+    if [ "${SELECTED_LIBRARY}" == '' ]; then
+      echo "Aborted."
+      exit 1;
+    fi
+
+    DEP=(${SELECTED_LIBRARY//:/ })
+    GROUPID=${DEP[0]}
+    DEP=(${DEP[1]//_/ })
+    ARTIFACTID=${DEP[0]}
+    REVISION=${DEP[1]}
+    LIBRARY="\"$GROUPID\" % \"$ARTIFACTID\" % \"$REVISION\""
+
     # @todo check if the library is already installed, dedup dependencies
-    echo -e "\nlibraryDependencies += \"$groupID\" % \"$artifactID\" % \"$revision\"" >> $SBT_FILE
+    echo -e "\nlibraryDependencies += $LIBRARY" >> $SBT_FILE
+
+    echo "Installing $LIBRARY..."
     sbt update
     ;;
 
